import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "next-themes";
import OCConnectWrapper from "@/components/oc-connect-wrapper";
import "@opencampus/ocid-connect-js/lib/react/OCSpinner.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const opts = {
		clientId: process.env.NEXT_PUBLIC_OCID_CLIENT_ID!,
		redirectUri:
			process.env.NEXT_PUBLIC_OCID_REDIRECT_URI! ||
			"http://localhost:3000/redirect",
		referralCode: "PARTNER6",
	};

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NextTopLoader
					showSpinner={false}
					color="#84cc16"
					initialPosition={0.04}
					crawlSpeed={300}
					height={2}
					crawl={true}
					easing="ease"
					speed={350}
					shadow="0 0 10px #84cc16,0 0 5px #84cc16"
					zIndex={9999}
				/>
				<OCConnectWrapper opts={opts} sandboxMode={true}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</OCConnectWrapper>
				<Toaster richColors closeButton />
			</body>
		</html>
	);
}
