import fs from "fs";
import path from "path";
import prettier from "prettier";
import { artifacts, deployments, ethers } from "hardhat";

/**
 * @deprecated Use the overload with `networkId` instead.
 *
 * Writes deployment addresses and ABIs to a given app's deployments directory.
 *
 * @param appPath - Base path of the app (relative to __dirname).
 * @param addresses - Deployment addresses object.
 * @param contractNames - List of contract names to export ABIs for.
 */
export async function exportDeployments(
    appPath: string,
    addresses: Record<string, any>,
    contractNames: string[]
): Promise<void>;

/**
 * Writes or updates a single TypeScript file containing deployed contracts for a given app.
 * If the file already exists, it will merge in the new network instead of overwriting.
 *
 * @param appPath - Base path of the app (relative to __dirname).
 * @param addresses - Deployment addresses object (keyed by contract name).
 * @param contractNames - List of contract names to include.
 * @param networkId - Chain ID (e.g. 31337 for Hardhat).
 */
export async function exportDeployments(
    appPaths: string[],
    contractMap: Record<string, string>
): Promise<void>;

export async function exportDeployments(
    appPaths: string[],
    contractMap: Record<string, string>
): Promise<void> {
    if (!Array.isArray(appPaths)) {
        throw new Error("DEPRECATED: appPaths must be an array of strings.");
    }

    const networkId = Number((await ethers.provider.getNetwork()).chainId);

    const contracts: Record<string, { address: string; abi: any }> = {};
    const { save, getExtendedArtifact } = deployments;

    for (const [name, address] of Object.entries(contractMap)) {
        const artifact = await artifacts.readArtifact(name);
        contracts[name] = {
            address: address,
            abi: artifact.abi,
        };

        const { abi, metadata } = await getExtendedArtifact(name);
        await save(name, { abi, metadata, address });
        console.log(`📁 Saved artifact for ${name} at ${address}`);
    }

    for (const appPath of appPaths) {
        const deploymentsDir = path.join(appPath);
        if (!fs.existsSync(deploymentsDir))
            fs.mkdirSync(deploymentsDir, { recursive: true });

        const outFile = deploymentsDir.endsWith(".ts")
            ? deploymentsDir
            : path.join(deploymentsDir, "deployedContracts.ts");

        console.log("📝 Exporting deployment artifacts to", outFile);

        // Load existing deployments if file exists
        let existing: Record<string, any> = {};
        if (fs.existsSync(outFile)) {
            existing = extractObjectFromTs(outFile, "deployedContracts");
        }

        // Merge current network
        existing[networkId] = contracts;

        // Generate TypeScript output
        const output = `/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */

export const deployedContracts = ${JSON.stringify(existing, null, 2)} as const;
`;

        fs.writeFileSync(
            outFile,
            await prettier.format(output, { parser: "typescript" })
        );
    }
}

export function extractObjectFromTs(
    filePath: string,
    objectName: string
): {
    [key: string]: {
        [key: string]: {
            address: string;
            abi: any;
        };
    };
} {
    const content = fs.readFileSync(filePath, "utf8");

    // Step 1: Find "export const deployedContracts = {"
    const startRegex = new RegExp(`export\\s+const\\s+${objectName}\\s*=\\s*{`);

    const startMatch = content.match(startRegex);
    if (!startMatch) throw new Error(`Object '${objectName}' not found`);

    const startIndex = startMatch.index! + startMatch[0].length - 1;

    // Step 2: Extract full object literal using brace balancing
    let i = startIndex;
    let braceCount = 0;
    let inString: string | null = null;

    while (i < content.length) {
        const char = content[i];

        // Handle string boundaries to avoid breaking inside strings
        if (char === '"' || char === "'" || char === "`") {
            if (!inString) {
                inString = char;
            } else if (inString === char) {
                inString = null;
            }
        }

        if (!inString) {
            if (char === "{") braceCount++;
            if (char === "}") braceCount--;
            if (braceCount === 0) {
                i++;
                break;
            }
        }

        i++;
    }

    const rawObject = content.slice(
        startMatch.index! + startMatch[0].length - 1,
        i
    );

    // Step 3: Clean TS syntax for safe JSON parsing
    let cleaned = rawObject
        .replace(/as const;?/g, "") // remove 'as const'
        .replace(/(\w+):/g, '"$1":') // unquoted property keys → quoted
        .replace(/,(\s*[}\]])/g, "$1"); // remove trailing commas

    // Remove comments
    cleaned = cleaned
        .replace(/\/\*[\s\S]*?\*\//g, "") // block comments
        .replace(/\/\/.*/g, ""); // line comments

    // Step 4: Parse
    try {
        return JSON.parse(cleaned);
    } catch (err) {
        console.error("Failed to parse JSON. Cleaned text:\n", cleaned);
        throw err;
    }
}
