import fs from "fs";
import path from "path";
import { artifacts } from "hardhat";
import prettier from "prettier";

/**
 * @deprecated Use the overload with `networkId` instead.
 *
 * Writes deployment addresses and ABIs to a given app's deployments directory.
 *
 * @param appPath - Base path of the app (relative to __dirname).
 * @param addresses - Deployment addresses object.
 * @param contractNames - List of contract names to export ABIs for.
 */
export async function exportDeployments(
    appPath: string,
    addresses: Record<string, any>,
    contractNames: string[]
): Promise<void>;

/**
 * Writes or updates a single TypeScript file containing deployed contracts for a given app.
 * If the file already exists, it will merge in the new network instead of overwriting.
 *
 * @param appPath - Base path of the app (relative to __dirname).
 * @param addresses - Deployment addresses object (keyed by contract name).
 * @param contractNames - List of contract names to include.
 * @param networkId - Chain ID (e.g. 31337 for Hardhat).
 */
export async function exportDeployments(
    appPath: string,
    addresses: Record<string, any>,
    contractNames: string[],
    contracts: Record<string, string>,
    networkId: number
): Promise<void>;

export async function exportDeployments(
    appPath: string,
    addresses: Record<string, any>,
    contractNames: string[],
    contractMap?: Record<string, string>,
    networkId?: number
): Promise<void> {
    const deploymentsDir = path.join(appPath);
    fs.mkdirSync(deploymentsDir, { recursive: true });

    if (
        typeof networkId === "undefined" ||
        typeof contractMap === "undefined"
    ) {
        // --------------------------
        // Deprecated JSON + abis mode
        // --------------------------
        const deploymentsPath = path.join(deploymentsDir, "deployments.json");
        fs.writeFileSync(deploymentsPath, JSON.stringify(addresses, null, 2));

        const abiDir = path.join(deploymentsDir, "abis");
        fs.mkdirSync(abiDir, { recursive: true });

        for (const name of contractNames) {
            const artifact = await artifacts.readArtifact(name);
            fs.writeFileSync(
                path.join(abiDir, `${name}.json`),
                JSON.stringify(artifact, null, 2)
            );
        }
    } else {
        // --------------------------
        // New TS single-file mode with merging
        // --------------------------
        const contracts: Record<string, { address: string; abi: any }> = {};

        for (const [name, address] of Object.entries(contractMap)) {
            const artifact = await artifacts.readArtifact(name);
            contracts[name] = {
                address: address,
                abi: artifact.abi,
            };
        }

        const outFile = path.join(deploymentsDir, "deployedContracts.ts");

        // Load existing deployments if file exists
        let existing: Record<string, any> = {};
        if (fs.existsSync(outFile)) {
            try {
                // Dynamically import the module
                const mod = await import(outFile);
                if (mod.deployedContracts) {
                    existing = mod.deployedContracts;
                }
            } catch (err) {
                console.error(
                    "❌ Failed to import deployedContracts:",
                    (err as Error).message
                );
                existing = {};
            }
        }

        console.log({ existing });

        // Merge current network
        existing[networkId] = contracts;

        // Generate TypeScript output
        const output = `/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */

export const deployedContracts = ${JSON.stringify(existing, null, 2)} as const;
`;

        fs.writeFileSync(
            outFile,
            await prettier.format(output, { parser: "typescript" })
        );
    }
}
